apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: <REPO>-service-aicollaboration.net
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
spec:
  tls:
    - hosts:
        - aicollaboration.net
        - aicollaboration.com
      secretName: tls-latest-aiproduct.io
  rules:
    - host: <REPO>.service.aicollaboration.net
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: <REPO>
                port:
                  number: 5000
