apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: text-summarization-service-aicollaboration.net
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($host = 'www.aicollaboration.net' ) {
        rewrite ^/(.*)$ https://aicollaboration.net/$1 permanent;
      }
spec:
  tls:
    - hosts:
        - aicollaboration.net
        - www.aicollaboration.net
      secretName: tls-latest-aiproduct.io
  rules:
    - host: text-summarization.service.aicollaboration.net
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: <REPO>
                port:
                  number: 5000
