apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-summarization
  labels:
    app: text-summarization
spec:
  replicas: 3
  selector:
    matchLabels:
      app: text-summarization
  template:
    metadata:
      labels:
        app: text-summarization
    spec:
      containers:
        - name: text-summarization
          image: "aicollaboration/text-summarization:latest"
          imagePullPolicy: Always
          env:
            - name: PYTHONUNBUFFERED
              value: "0"
          ports:
            - containerPort: 5000
      restartPolicy: Always
