apiVersion: apps/v1
kind: Deployment
metadata:
  name: <REPO>
  labels:
    app: <REPO>
spec:
  replicas: 3
  selector:
    matchLabels:
      app: <REPO>
  template:
    metadata:
      labels:
        app: <REPO>
    spec:
      containers:
        - name: <REPO>
          image: "aicollaboration/<REPO>:<VERSION>"
          imagePullPolicy: Always
          env:
            - name: PYTHONUNBUFFERED
              value: "0"
          ports:
            - containerPort: 5000
      restartPolicy: Always
