apiVersion: v1
kind: Service
metadata:
  namespace: 5elementsofai
  name: text-summarization
  labels:
    service: text-summarization
spec:
  type: LoadBalancer
  selector:
    app: text-summarization
  ports:
    - port: 5000
      targetPort: 5000
