openapi: 3.1.0
info:
  title: Micro model service for text summarization
  version: 1.0.0
  description: It will use a pretrained bert
servers:
  - url: http://localhost:5080
paths:
  /api/1.0/ping:
    get:
      operationId: ping
      responses:
        200:
          description: It will return a pong when everything if correct
  /api/1.0/info:
    get:
      operationId: info
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Info"
  /api/1.0/definition:
    get:
      operationId: definition
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Definition"
  /api/1.0/predict:
    post:
      operationId: predict
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Input"
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Output"
components:
  schemas:
    Info:
      type: object
      properties:
        version:
          type: string
        project:
          type: string
        service:
          type: string
        language:
          type: string
        type:
          type: string
        date:
          type: string
          format: date-time
    Definition:
      type: object
    Input:
      type: object
      properties:
        context:
          type: string
          description: The text you want to summarize
        config:
          type:  object
          description: The configs you can submit
          properties: 
            max_length:
              type: string
              description: The length you want the summarization to be
    Output:
      type: object
      properties:
        summary:
          type: string
