apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-summarization
spec:
  replicas: {{ .Values.textsummarization.replicaCount }}
  selector:
    matchLabels:
      app: text-summarization
  template:
    metadata:
      labels:
        app: text-summarization
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: text-summarization
          image: "{{ .Values.textsummarization.image }}:{{ .Values.tag }}"
          env:
          - name: PYTHONUNBUFFERED
            value: "0"
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: "4096Mi"
              cpu: "1"
